#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# Set up a NAMED Cloudflare tunnel — a permanent URL that survives restarts.
#
#   ./setup-named-tunnel.sh yourdomain.com [subdomain]
#
# Default subdomain is "pickleball", giving https://pickleball.yourdomain.com
#
# REQUIREMENTS (both free, but unavoidable):
#   1. A Cloudflare account
#   2. A domain whose nameservers point at Cloudflare
#
# Why: quick tunnels get a random trycloudflare.com name that Cloudflare
# rotates on every restart. A stable hostname has to live under a zone you
# control — there's no way around owning a domain. Cheapest route is a ~$5/yr
# name from Cloudflare Registrar / Namecheap, then "Add site" in Cloudflare.
#
# If you'd rather not buy a domain, skip this and use ./install-agents.sh
# (quick mode) plus ./whats-my-url.sh, or ask about the Tailscale option —
# stable hostname, free, no domain, but every friend installs an app.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

DOMAIN="${1:-}"
SUB="${2:-pickleball}"
PORT="${PORT:-8777}"
APP_DIR="$(cd "$(dirname "$0")" && pwd)"
TUNNEL_NAME="pickleball-elo"

if [[ -z "$DOMAIN" ]]; then
  cat <<USAGE
Usage: ./setup-named-tunnel.sh yourdomain.com [subdomain]

You need a Cloudflare account and a domain on Cloudflare's nameservers.
Without one, a permanent URL isn't possible — use quick mode instead:
    ./install-agents.sh

USAGE
  exit 1
fi

HOSTNAME="$SUB.$DOMAIN"
command -v cloudflared >/dev/null || { echo "✗ brew install cloudflared"; exit 1; }

echo "  domain    $DOMAIN"
echo "  hostname  $HOSTNAME"
echo "  tunnel    $TUNNEL_NAME"
echo

# ── 1. authenticate (opens a browser) ───────────────────────────────────────
if [[ ! -f "$HOME/.cloudflared/cert.pem" ]]; then
  echo "── Step 1: authorize cloudflared ──"
  echo "  A browser will open. Pick $DOMAIN from your Cloudflare zones."
  echo
  cloudflared tunnel login
else
  echo "✓ already authorized (~/.cloudflared/cert.pem exists)"
fi

# ── 2. create the tunnel (idempotent) ───────────────────────────────────────
if cloudflared tunnel list 2>/dev/null | awk '{print $2}' | grep -qx "$TUNNEL_NAME"; then
  echo "✓ tunnel '$TUNNEL_NAME' already exists"
else
  echo "── Step 2: create tunnel ──"
  cloudflared tunnel create "$TUNNEL_NAME"
fi

TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null \
  | awk -v n="$TUNNEL_NAME" '$2==n {print $1}' | head -1)
[[ -z "$TUNNEL_ID" ]] && { echo "✗ couldn't determine tunnel ID"; exit 1; }
echo "  tunnel id: $TUNNEL_ID"

# ── 3. config file ──────────────────────────────────────────────────────────
CFG_DIR="$HOME/.cloudflared"
cat > "$CFG_DIR/config.yml" <<YML
# Generated by setup-named-tunnel.sh for Pickleball Elo
tunnel: $TUNNEL_ID
credentials-file: $CFG_DIR/$TUNNEL_ID.json

ingress:
  - hostname: $HOSTNAME
    service: http://localhost:$PORT
  # Catch-all: anything else that reaches this tunnel gets refused rather
  # than silently proxied somewhere unexpected.
  - service: http_status:404
YML
echo "✓ wrote $CFG_DIR/config.yml"

# ── 4. DNS route ────────────────────────────────────────────────────────────
echo "── Step 4: point DNS at the tunnel ──"
if cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME" 2>&1 | tee /tmp/cfdns.txt; then
  echo "✓ DNS routed"
else
  if grep -qi 'already exists\|record with that host' /tmp/cfdns.txt; then
    echo "✓ DNS record already present"
  else
    echo "⚠ DNS routing had a problem — check the output above."
    echo "  You can add a CNAME manually in the Cloudflare dashboard:"
    echo "     $HOSTNAME  →  $TUNNEL_ID.cfargotunnel.com  (proxied)"
  fi
fi

# ── 5. remember it for the agent installer ──────────────────────────────────
echo "$TUNNEL_NAME" > "$APP_DIR/.tunnel-name"
echo "$HOSTNAME"    > "$APP_DIR/.tunnel-hostname"

cat <<DONE

──────────────────────────────────────────────────────────────
✓ Named tunnel ready.

  Permanent URL:  https://$HOSTNAME

Now install the agents so it all starts on login:

    ./install-agents.sh named

DNS can take a minute or two to propagate the first time. After that the
URL never changes — bookmark it, share it once, done.
──────────────────────────────────────────────────────────────
DONE
